M48
; DRILL file {KiCad 9.0.7} date 2026-01-19T21:11:16+1000
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-01-19T21:11:16+10:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.600
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.991
%
G90
G05
T1
X99.2Y-66.1
T2
X51.38Y-60.11
X51.38Y-65.89
T3
X54.299Y-73.34
X55.315Y-68.26
X56.331Y-73.34
M30
