M48
; DRILL file {KiCad 9.0.6} date 2025-12-03T09:56:24+1000
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-12-03T09:56:24+10:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.300
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.991
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C3.450
%
G90
G05
T1
X93.0Y-72.0
T2
X51.43Y-60.11
X51.43Y-65.89
T3
X61.298Y-80.599
X62.314Y-75.519
X63.33Y-80.599
T4
X62.14Y-89.7
X92.11Y-85.0
M30
